spring:
  application:
    name: service-oss
  datasource:
    username: root_he
    password: Bdtrysb2
    url: jdbc:mysql://rm-bp1vfj2tm8i1bz6e6yo.mysql.rds.aliyuncs.com:3306/algorithm?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.algorithm.mapper

server:
  port: 8089

aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5t8SJNjRm7VGsUUXLTEb
      keysecret: rg5EhokfmJFXMY8t2KKC2l6IL6NNGH
      bucketname: katechian-algorithm
